spring.application.name=demosigea-backend
# ===================================
# CONEXIÓN A BASE DE DATOS NEON (POSTGRESQL)
# ===================================
spring.datasource.url=jdbc:postgresql://ep-autumn-firefly-b5dumshb-pooler.c-7.us-east-2.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_LrmUFwa69xeB
spring.datasource.driver-class-name=org.postgresql.Driver

# ===================================
# CONFIGURACIÓN DE HIBERNATE / JPA
# ===================================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Permite que Spring Boot cree/actualice las tablas automáticamente según tus entidades Java
spring.jpa.hibernate.ddl-auto=update

# Muestra las consultas SQL en la consola durante el desarrollo
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true